'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,WifiOff,X,Share,PlusSquare,Check} from 'lucide-react';
type InstallEvent=Event&{prompt:()=>Promise<void>,userChoice:Promise<{outcome:string}>};
export default function PWA(){
 const [online,setOnline]=useState(true),[installed,setInstalled]=useState(false),[help,setHelp]=useState(false),[ios,setIos]=useState(false),[canInstall,setCanInstall]=useState(false);
 const deferred=useRef<InstallEvent|null>(null);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();setIos(/iPhone|iPad|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1));const media=window.matchMedia('(display-mode: standalone)');const standalone=()=>setInstalled(media.matches||!!(navigator as Navigator&{standalone?:boolean}).standalone);standalone();const install=(event:Event)=>{event.preventDefault();deferred.current=event as InstallEvent;setCanInstall(true)};const done=()=>{setInstalled(true);setCanInstall(false);deferred.current=null};window.addEventListener('online',update);window.addEventListener('offline',update);window.addEventListener('beforeinstallprompt',install);window.addEventListener('appinstalled',done);media.addEventListener('change',standalone);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(()=>{});return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);window.removeEventListener('beforeinstallprompt',install);window.removeEventListener('appinstalled',done);media.removeEventListener('change',standalone)}},[]);
 async function install(){const event=deferred.current;if(event){await event.prompt();const result=await event.userChoice;if(result.outcome==='accepted')setInstalled(true);deferred.current=null;setCanInstall(false);}else setHelp(true)}
 return <><div className={'connection '+(!online?'disconnected':'')} role="status"><span/>{online?'Dalam talian':'Tiada internet'}</div>{!installed&&<button className="install-button secondary" onClick={install}><Download size={16}/><span>Pasang POS</span></button>}{!online&&<div className="offline-bar" role="alert"><WifiOff size={17}/>Sambungan terputus. Bayaran dan perubahan memerlukan internet.</div>}{help&&<div className="overlay"><section className="dialog install-dialog" role="dialog" aria-modal="true" aria-labelledby="install-title"><button className="close" aria-label="Tutup pemasangan" onClick={()=>setHelp(false)}><X/></button><img className="install-icon" src="/icons/icon-192.png" alt="Ikon Rumah Kedua"/><h2 id="install-title">Rumah Kedua di skrin utama.</h2><p>Buka kaunter seperti aplikasi, terus dari telefon atau komputer.</p>{ios?<ol><li>Buka pautan POS ini dalam Safari.</li><li>Tekan <Share size={16}/> <strong>Share</strong>.</li><li>Pilih <PlusSquare size={16}/> <strong>Add to Home Screen</strong>, kemudian Add.</li></ol>:<p>Pada Chrome atau Edge, buka menu browser dan pilih <strong>Install app</strong> atau <strong>Add to Home screen</strong> jika tersedia.</p>}<div className="install-note"><Check size={17}/>Guna alamat domain yang sama untuk kaunter dan dapur.</div><button className="primary full" onClick={()=>setHelp(false)}>Faham</button></section></div>}</>;
}
